<a href="https://colab.research.google.com/github/saichanduchinnam01/DEEPLEARNING_FINAL/blob/main/DEEP_LEARNING_ALL_EXPERIMENTS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.A.DIMENSIONS CREATING AND MANIPULATING TENSORS
import tensorflow as tf
try:
 tf.executing_eagerly()
 print("TF imported with eager execution!")
except ValueError:
 print("TF already imported with eager execution!")
primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
print("primes:", primes)
ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)
just_beyond_primes = tf.add(primes, ones)
print("just_beyond_primes:", just_beyond_primes)
twos = tf.constant([2, 2, 2, 2, 2, 2], dtype=tf.int32)
primes_doubled = primes * twos
print("primes_doubled:", primes_doubled)
some_matrix = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())

TF imported with eager execution!
primes: tf.Tensor([ 2  3  5  7 11 13], shape=(6,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)
just_beyond_primes: tf.Tensor([ 3  4  6  8 12 14], shape=(6,), dtype=int32)
primes_doubled: tf.Tensor([ 4  6 10 14 22 26], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

value of some_matrix is:
 [[1 2 3]
 [4 5 6]]


In [ ]:
#1.B.TRAIN AND EVALUATE

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

# Load and preprocess the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
y_train, y_test = to_categorical(y_train, 10), to_categorical(y_test, 10)
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2)
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_accuracy:.4f}")


11490434/11490434 [==============================] - 1s 0us/step
Epoch 1/5
1500/1500 [==============================] - 17s 9ms/step - loss: 0.2665 - accuracy: 0.9210 - val_loss: 0.1449 - val_accuracy: 0.9567
Epoch 2/5
1500/1500 [==============================] - 6s 4ms/step - loss: 0.1105 - accuracy: 0.9660 - val_loss: 0.1062 - val_accuracy: 0.9678
Epoch 3/5
1500/1500 [==============================] - 5s 4ms/step - loss: 0.0759 - accuracy: 0.9766 - val_loss: 0.0941 - val_accuracy: 0.9724
Epoch 4/5
1500/1500 [==============================] - 7s 5ms/step - loss: 0.0574 - accuracy: 0.9819 - val_loss: 0.0952 - val_accuracy: 0.9716
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0818 - accuracy: 0.9772
Test accuracy: 0.9772
